-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------



SHOW TABLES IN lakeflow.divya;

-- Query gold city trip volumes
SELECT * 
FROM lakeflow.divya.gold_city_trip_volumes
ORDER BY total_trips DESC;




-- COMMAND ----------

-- Query peak hour volumes
SELECT* 
FROM lakeflow.divya.gold_peak_hours
ORDER BY trips_in_hour DESC;


-- COMMAND ----------



-- Query customer activity trends
SELECT * 
FROM lakeflow.divya.gold_customer_activity
ORDER BY total_trips DESC;
